---     
driver_plugin: vagrant
driver_config:
  box: opscode-centos-6.3
  box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
platforms:
- name: app-server
  run_list: [ "recipe[yumrepo::epel]" ]
  driver_config:
    network: { hostonly: '33.33.33.20' }
- name: load-balancer
  run_list: [ "yumrepo::epel", "recipe[tk-haproxy]" ]
  attributes:
    tk_haproxy: { backend_ips: [ '33.33.33.20' ] }
  driver_config:
    network:
      hostonly: '33.33.33.21'
- name: apache-frontend
  run_list: [ "recipe[yumrepo::epel]", "recipe[tk-apache2]" ]
  attributes:
    tk_apache2: { load_balancers: [ '33.33.33.21' ] }
  driver_config:
    forward_port: [80, 8080]
    network:
      hostonly: '33.33.33.22'
suites:
- name: default
  run_list: []